# Chapter 12: Cost Anomaly Detection with Prometheus Rules
# Listing 12.8 - Prometheus alerting rules for cost anomalies
# Detects unusual cost spikes by comparing current rates against 7-day baselines.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cost-anomalies
  namespace: monitoring
spec:
  groups:
    - name: cost-anomalies
      interval: 5m
      rules:
        # Primary cost anomaly detection — compares current 1h CPU rate
        # against the 7-day average using PromQL subquery syntax [7d:1h]
        - alert: CostAnomalyDetected
          expr: |
            abs(
              sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))
              - avg_over_time(sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))[7d:1h])
            )
            >
            0.5 * avg_over_time(sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))[7d:1h])
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Cost anomaly detected"
            description: >
              Namespace {{ $labels.namespace }} CPU cost has deviated
              by more than 50% from its 7-day baseline

        # Alert for oversized pod resource requests (request/usage ratio > 3x)
        - alert: OversizedPods
          expr: |
            (
              kube_pod_container_resource_requests{resource="cpu"}
              / on(namespace, pod, container) (rate(container_cpu_usage_seconds_total[5m]) + 0.001)
            ) > 3
          for: 15m
          labels:
            severity: info
            category: resource-optimization
          annotations:
            summary: "Pod has oversized resource requests compared to actual usage"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has request/usage ratio of {{ $value }}x (threshold: 3x)"

        # Alert for low node utilization
        - alert: LowNodeUtilization
          expr: |
            (1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) < 0.2
          for: 30m
          labels:
            severity: info
            category: efficiency
          annotations:
            summary: "Node has low CPU utilization"
            description: "Node {{ $labels.instance }} CPU utilization below 20% — consider consolidating workloads"

        # Namespace-level cost anomaly using subquery syntax
        - alert: NamespaceCostAnomaly
          expr: |
            abs(
              sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))
              - avg_over_time(sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))[7d:1h])
            )
            > 2 * stddev_over_time(sum by (namespace) (rate(container_cpu_usage_seconds_total[1h]))[7d:1h])
          for: 5m
          labels:
            severity: warning
            category: cost-anomaly
          annotations:
            summary: "Namespace cost anomaly detected"
            description: "Namespace {{ $labels.namespace }} resource usage deviates by >2 standard deviations from its 7-day average"
