apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecost-allocation-config
  namespace: kubecost
data:
  allocation.yaml: |
    # KubeCost Cost Allocation Configuration
    # Enables team-based cost reporting with custom labels
    
    # Custom label mappings for cost allocation
    custom_labels:
      - name: team
        key: team
        description: "Team responsible for the workload"
      
      - name: cost-center
        key: cost-center
        description: "Cost center for billing allocation"
      
      - name: environment
        key: environment
        values:
          - production
          - staging
          - development
        description: "Deployment environment"
    
    # Aggregation configuration
    aggregation:
      # Aggregate costs by namespace
      - dimension: namespace
        label: "Namespace"
      
      # Aggregate costs by team label
      - dimension: label:team
        label: "Team"
      
      # Aggregate costs by cost-center
      - dimension: label:cost-center
        label: "Cost Center"
      
      # Aggregate costs by environment
      - dimension: label:environment
        label: "Environment"
    
    # Cost allocation rules
    allocation_rules:
      # Shared costs allocation
      - type: shared
        source: label:team
        distribution: "equal"
      
      # Idle resources allocation
      - type: idle
        source: label:cost-center
        distribution: "proportional"
    
    # Filters for allocation
    filters:
      - exclude_namespaces:
          - kube-system
          - kube-public
          - kubecost
      - exclude_labels:
          - "temporary=true"
