# GitHub Actions Reusable Workflow: Platform Release Workflow
#
# This workflow demonstrates the release workflow pattern described in Chapter 1:
# 1. Build - Compile and package code
# 2. Test - Run unit and integration tests
# 3. Security Scan - Static analysis and vulnerability scanning
# 4. Deploy to Staging - Automated staging deployment
# 5. Approval Gate - Manual approval before production
# 6. Deploy to Production - Automated production deployment
#
# Usage in your workflow:
#   jobs:
#     release:
#       uses: ./.github/workflows/release-workflow.yaml
#       with:
#         service-name: my-service
#         environment: production
#       secrets:
#         REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

name: Platform Release Workflow

on:
  workflow_call:
    inputs:
      service-name:
        description: 'Name of the service being released'
        required: true
        type: string
      environment:
        description: 'Target environment for deployment'
        required: false
        type: string
        default: 'staging'
      docker-registry:
        description: 'Docker registry URL'
        required: false
        type: string
        default: 'docker.io'
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

env:
  REGISTRY: ${{ inputs.docker-registry }}
  SERVICE_NAME: ${{ inputs.service-name }}

jobs:
  # Stage 1: Build
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.SERVICE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Stage 2: Test
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov

      - name: Run unit tests
        run: |
          pytest tests/unit -v --cov=src

      - name: Run integration tests
        run: |
          pytest tests/integration -v
        continue-on-error: true

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  # Stage 3: Security Scan
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'

      - name: Run SAST analysis
        run: |
          # Example: Using semgrep for static analysis
          echo "Running static analysis on source code..."
          # pip install semgrep
          # semgrep --config=p/security-audit src/
        continue-on-error: true

  # Stage 4: Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to staging
        run: |
          echo "Deploying ${{ env.SERVICE_NAME }} to staging environment..."
          # For Kind clusters, set KUBECONFIG to your cluster config
          # kubectl apply -f k8s/staging/deployment.yaml
          # or helm upgrade --install ${{ env.SERVICE_NAME }} ./helm-chart -f values-staging.yaml
          echo "✓ Deployment to staging completed"

      - name: Health check
        run: |
          echo "Running health checks on staging deployment..."
          # Add health check endpoints
          # curl -f https://staging.example.com/health || exit 1
          echo "✓ Health checks passed"

      - name: Run smoke tests
        run: |
          echo "Running smoke tests against staging..."
          # pytest tests/smoke -v
          echo "✓ Smoke tests passed"

  # Stage 5: Approval Gate
  approval-gate:
    name: Approval for Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production-approval
    steps:
      - name: Request approval
        run: |
          echo "Waiting for approval to deploy to production..."
          echo "Build: ${{ github.sha }}"
          echo "Service: ${{ env.SERVICE_NAME }}"

  # Stage 6: Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: approval-gate
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to production
        run: |
          echo "Deploying ${{ env.SERVICE_NAME }} to production..."
          # kubectl apply -f k8s/production/deployment.yaml
          echo "✓ Deployment to production completed"

      - name: Verify production deployment
        run: |
          echo "Verifying production deployment..."
          # Add verification commands
          echo "✓ Production deployment verified"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ env.SERVICE_NAME }} v${{ github.run_number }}
          draft: false
          prerelease: false
