# Chapter 3 - Securing Platform Access
# Kubernetes ServiceAccount for CI/CD Pipeline
#
# This ServiceAccount is used by the CI/CD pipeline to deploy
# workloads into the platform. It follows the principle of least
# privilege and is bound to specific roles via RoleBindings.
#
# Usage:
#   1. Apply this manifest: kubectl apply -f service-account.yaml
#   2. Create a RoleBinding to grant permissions (see rbac-developer-role.yaml)
#   3. Generate a token: kubectl create token cicd-deployer -n platform
#
# Security considerations:
#   - automountServiceAccountToken is set to false by default
#   - Token must be explicitly mounted only in pods that need it
#   - Rotate tokens regularly using short-lived TokenRequest API

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: platform
  labels:
    app.kubernetes.io/part-of: platform-engineering
    app.kubernetes.io/component: cicd
    team: platform
    cost-center: "PE-1001"
  annotations:
    description: "Service account for CI/CD pipeline deployments"
    # Disable automatic token mounting for security
automountServiceAccountToken: false

---
# Short-lived token configuration for CI/CD usage
# Use: kubectl create token cicd-deployer -n platform --duration=1h
#
# For long-running pipelines, use a Secret-based token (not recommended):
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cicd-deployer-token
#   namespace: platform
#   annotations:
#     kubernetes.io/service-account.name: cicd-deployer
# type: kubernetes.io/service-account-token

---
# Role: CI/CD deployment permissions (least-privilege)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-deployer
  namespace: platform
  labels:
    app.kubernetes.io/part-of: platform-engineering
    app.kubernetes.io/component: cicd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# RoleBinding: Grant the CI/CD service account deployment permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-deployer-binding
  namespace: platform
  labels:
    app.kubernetes.io/part-of: platform-engineering
    app.kubernetes.io/component: cicd
subjects:
  - kind: ServiceAccount
    name: cicd-deployer
    namespace: platform
roleRef:
  kind: Role
  name: platform-deployer    # References a Role with deploy-specific permissions
  apiGroup: rbac.authorization.k8s.io
