apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: resilience-test-workflow
  namespace: chaos-testing
spec:
  # Workflow entry point
  entrypoint: resilience-test
  
  # Service account for workflow execution
  serviceAccountName: chaos-mesh
  
  # Templates define the workflow steps
  templates:
    # Main workflow template
    - name: resilience-test
      steps:
        # Step 1: Pod failure test
        - - name: pod-failure-step
            template: pod-failure-template
              arguments: {}
        
        # Step 2: Network delay test (after pod failure completes)
        - - name: network-delay-step
            template: network-delay-template
              arguments: {}
        
        # Step 3: Verification and recovery check
        - - name: verify-recovery-step
            template: verify-recovery-template
              arguments: {}
    
    # Template for pod failure chaos
    - name: pod-failure-template
      chaos:
        action: pod-kill
        selector:
          namespaces:
            - team-alpha
          labelSelectors:
            app: demo-app
        mode: fixed-percent
        value: "30"
        duration: 30s
        gracePeriod: 5
    
    # Template for network delay chaos
    - name: network-delay-template
      chaos:
        action: network-delay
        selector:
          namespaces:
            - team-alpha
          labelSelectors:
            app: demo-app
        mode: one
        duration: 60s
        
        # Network delay parameters
        delaySpec:
          latency: 100ms
          jitter: 10ms
          correlation: 100
          reorder: "0%"
    
    # Template for verification and recovery
    - name: verify-recovery-template
      script:
        image: bitnami/kubectl:latest
        command: [sh]
        source: |
          #!/bin/bash
          set -e
          
          echo "=== Verifying cluster recovery ==="
          
          # Check pod status
          echo "Checking pod status..."
          kubectl get pods -n team-alpha -l app=demo-app -o wide
          
          # Wait for pods to be ready
          echo "Waiting for pods to be ready..."
          kubectl wait --for=condition=Ready pod \
            -l app=demo-app \
            -n team-alpha \
            --timeout=300s || echo "Warning: Some pods not ready within timeout"
          
          # Check deployment status
          echo "Checking deployment status..."
          kubectl get deployment demo-app -n team-alpha -o wide
          
          # Verify service endpoints
          echo "Verifying service endpoints..."
          kubectl get endpoints demo-app -n team-alpha
          
          # Test service connectivity
          echo "Testing service connectivity..."
          POD=$(kubectl get pod -n team-alpha -l app=demo-app -o jsonpath='{.items[0].metadata.name}')
          if [ -n "$POD" ]; then
            echo "Testing from pod: $POD"
            kubectl exec -it $POD -n team-alpha -- \
              wget -q -O- http://localhost:8080/health || echo "Service check completed"
          fi
          
          echo "=== Recovery verification complete ==="

---
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: cascading-failure-test
  namespace: chaos-testing
spec:
  entrypoint: cascading-test
  serviceAccountName: chaos-mesh
  
  templates:
    - name: cascading-test
      steps:
        # Step 1: Kill primary service pods
        - - name: kill-primary
            template: kill-service
            arguments:
              parameters:
                - name: service
                  value: demo-app
                - name: percentage
                  value: "50"
        
        # Step 2: Kill dependent service pods
        - - name: kill-dependent
            template: kill-service
            arguments:
              parameters:
                - name: service
                  value: database
                - name: percentage
                  value: "25"
        
        # Step 3: Inject network issues
        - - name: network-issues
            template: network-chaos
    
    - name: kill-service
      inputs:
        parameters:
          - name: service
          - name: percentage
      chaos:
        action: pod-kill
        selector:
          namespaces:
            - team-alpha
          labelSelectors:
            app: "{{ inputs.parameters.service }}"
        mode: fixed-percent
        value: "{{ inputs.parameters.percentage }}"
        duration: 60s
    
    - name: network-chaos
      chaos:
        action: network-delay
        selector:
          namespaces:
            - team-alpha
        mode: all
        duration: 90s
        delaySpec:
          latency: 200ms
          jitter: 50ms

---
apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: comprehensive-resilience-test
  namespace: chaos-testing
spec:
  entrypoint: comprehensive-test
  serviceAccountName: chaos-mesh
  parallelism: 2
  
  templates:
    - name: comprehensive-test
      dag:
        tasks:
          # Pod failure test
          - name: pod-failure
            template: pod-failure-chaos
          
          # Concurrent network test
          - name: network-test
            template: network-chaos-template
          
          # Depends on both above
          - name: verify
            template: verify-resilience
            dependencies: "pod-failure,network-test"
    
    - name: pod-failure-chaos
      chaos:
        action: pod-kill
        selector:
          namespaces:
            - team-alpha
          labelSelectors:
            app: demo-app
        mode: fixed-percent
        value: "40"
        duration: 45s
    
    - name: network-chaos-template
      chaos:
        action: network-loss
        selector:
          namespaces:
            - team-alpha
        mode: all
        duration: 60s
        lossSpec:
          loss: "10%"
          correlation: "25"
    
    - name: verify-resilience
      script:
        image: bitnami/kubectl:latest
        command: [sh]
        source: |
          echo "Verifying resilience after chaos tests..."
          kubectl get pods -n team-alpha -o wide
          echo "Resilience verification complete"
