apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-demo
  namespace: chaos-testing
spec:
  # Action type: kill the pod
  action: pod-kill
  
  # Duration of the chaos experiment
  duration: 30s
  
  # Selector for target pods
  selector:
    # Target specific namespace
    namespaces:
      - team-alpha
    
    # Match pods by label
    labelSelectors:
      app: demo-app
      version: v1
  
  # Mode of failure
  mode: one
  
  # Value depends on mode:
  # - mode: one → value is ignored
  # - mode: all → affects all matching pods
  # - mode: fixed → value is number of pods
  # - mode: fixed-percent → value is percentage
  
  # Recovery policy
  scheduler:
    cron: "@hourly"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-multiple
  namespace: chaos-testing
spec:
  # Action type
  action: pod-kill
  
  # Duration
  duration: 1m
  
  # Selector for target pods
  selector:
    namespaces:
      - team-alpha
      - team-beta
    
    labelSelectors:
      app: demo-app
  
  # Affect multiple pods (25% of matching pods)
  mode: fixed-percent
  value: "25"
  
  # Graceful period before pod termination
  gracePeriod: 5

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-all-replicas
  namespace: chaos-testing
spec:
  # Action type
  action: pod-kill
  
  # Duration
  duration: 45s
  
  # Selector
  selector:
    namespaces:
      - team-alpha
    
    labelSelectors:
      app: demo-app
  
  # Affect all matching pods
  mode: all
  
  # Graceful period
  gracePeriod: 10

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-experiment
  namespace: chaos-testing
spec:
  # Kill specific container instead of pod
  action: container-kill
  
  # Duration
  duration: 30s
  
  # Selector
  selector:
    namespaces:
      - team-alpha
    
    labelSelectors:
      app: demo-app
  
  # Container name to kill
  containerNames:
    - app
  
  # Mode
  mode: one
  
  # Graceful period
  gracePeriod: 0

---
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure-schedule
  namespace: chaos-testing
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  
  chaosSpec:
    apiVersion: chaos-mesh.org/v1alpha1
    kind: PodChaos
    metadata:
      name: pod-failure-scheduled
    spec:
      action: pod-kill
      duration: 30s
      selector:
        namespaces:
          - team-alpha
        labelSelectors:
          app: demo-app
      mode: fixed-percent
      value: "10"
      gracePeriod: 5
