apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  # Schedule daily backup at 2:00 AM UTC
  schedule: "0 2 * * *"
  
  # Template for backup configuration
  template:
    # Include specific namespaces
    includedNamespaces:
      - team-alpha
      - team-beta
      - production
    
    # Exclude system namespaces
    excludedNamespaces:
      - kube-system
      - kube-public
      - velero
    
    # Storage location for backup
    storageLocation: aws-s3
    
    # Snapshot location for volume snapshots
    volumeSnapshotLocation: aws-ebs
    
    # Include cluster resources
    includeClusterResources: true
    
    # Include namespace-scoped resources
    includedNamespaceScopedResources:
      - "pods"
      - "persistentvolumeclaims"
      - "deployments"
      - "statefulsets"
      - "daemonsets"
      - "configmaps"
      - "secrets"
      - "services"
    
    # TTL for backup retention (7 days = 168 hours)
    ttl: 168h
    
    # Backup hooks for pre-backup and post-backup operations
    hooks:
      resources:
        # Pre-backup hook: quiesce database
        - name: db-quiesce
          includedNamespaces:
            - team-alpha
          includedResources:
            - "pods"
          labelSelector:
            matchLabels:
              app: database
          pre:
            - exec:
                container: database
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Starting database quiesce..."
                    # Flush buffers and prepare for backup
                    redis-cli BGSAVE || true
                    sleep 5
                    echo "Database quiesce complete"
                timeout: 5m
        
        # Post-backup hook: resume operations
        - name: db-resume
          includedNamespaces:
            - team-alpha
          includedResources:
            - "pods"
          labelSelector:
            matchLabels:
              app: database
          post:
            - exec:
                container: database
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Resuming database operations..."
                    # Resume normal operations
                    echo "Database is operational"
                timeout: 2m
    
    # Snapshot settings for persistent volumes
    snapshotVolumes: true
    snapshotMoveData: false
    
    # Metadata options
    labels:
      schedule-type: daily
      backup-retention: "7days"
      backup-trigger: "schedule"
    
    # CSI snapshot configuration
    csiSnapshotTimeout: 10m
    
    # Partial backups allowed
    orderByClusterVersion: false

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup
  namespace: velero
spec:
  # Schedule hourly backup for critical namespaces
  schedule: "0 * * * *"
  
  template:
    includedNamespaces:
      - production
    
    excludedNamespaces:
      - kube-system
      - kube-public
      - velero
    
    storageLocation: aws-s3
    ttl: 72h  # Keep hourly backups for 3 days
    
    snapshotVolumes: true
    
    labels:
      schedule-type: hourly
      backup-retention: "3days"
