# Reusable workflow for security scanning
# Performs container image scanning, dependency scanning, and artifact signing
#
# Usage:
#   - uses: ./.github/workflows/reusable/security-scan.yaml
#     with:
#       scan-container: true
#       scan-dependencies: true
#       container-image: 'ghcr.io/myorg/myapp:latest'
#       artifact-path: 'dist/'

name: Security Scan

on:
  workflow_call:
    inputs:
      scan-container:
        required: false
        type: boolean
        description: 'Enable container image scanning'
        default: true
      scan-dependencies:
        required: false
        type: boolean
        description: 'Enable dependency scanning'
        default: true
      container-image:
        required: false
        type: string
        description: 'Container image to scan (optional)'
        default: ''
      artifact-path:
        required: false
        type: string
        description: 'Path to artifacts for SBOM generation'
        default: ''
      fail-on-critical:
        required: false
        type: boolean
        description: 'Fail workflow on critical vulnerabilities'
        default: true
    outputs:
      vulnerabilities-found:
        description: 'Whether vulnerabilities were found'
        value: ${{ jobs.security-scan.outputs.vulnerabilities-found }}
      sbom-path:
        description: 'Path to generated SBOM file'
        value: ${{ jobs.security-scan.outputs.sbom-path }}

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    outputs:
      vulnerabilities-found: ${{ steps.vulnscan.outputs.vulnerabilities-found }}
      sbom-path: sbom.json
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dependency Scanning with pip-audit (Python)
      - name: Scan Python dependencies
        if: inputs.scan-dependencies
        run: |
          python -m pip install pip-audit
          pip-audit --desc --format json > dependency-scan.json || true
          if grep -q '"vulnerabilities"' dependency-scan.json; then
            echo "⚠️  Found Python dependency vulnerabilities"
            cat dependency-scan.json
          else
            echo "✓ No Python dependency vulnerabilities found"
          fi
        continue-on-error: ${{ !inputs.fail-on-critical }}

      # Dependency Scanning with npm audit (Node.js)
      - name: Scan Node.js dependencies
        if: inputs.scan-dependencies && hashFiles('package.json') != ''
        run: |
          npm audit --json > dependency-scan-npm.json || true
          if grep -q '"vulnerabilities"' dependency-scan-npm.json; then
            echo "⚠️  Found npm dependency vulnerabilities"
            cat dependency-scan-npm.json
          else
            echo "✓ No npm dependency vulnerabilities found"
          fi
        continue-on-error: true

      # Container Image Scanning with Trivy
      - name: Run Trivy container scan
        if: inputs.scan-container && inputs.container-image != ''
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.container-image }}
          format: 'json'
          output: 'trivy-scan.json'
          exit-code: ${{ inputs.fail-on-critical && '1' || '0' }}
          ignore-unfixed: false
          severity: 'CRITICAL,HIGH'

      # Generate SBOM (Software Bill of Materials)
      - name: Generate SBOM with CycloneDX
        if: inputs.scan-dependencies || inputs.artifact-path != ''
        run: |
          python -m pip install cyclonedx-python-poetry
          if [ -f pyproject.toml ] || [ -f requirements.txt ]; then
            python -m cyclonedx.bom --output-file sbom.json
          fi
          if [ -f package.json ]; then
            npm install -g @cyclonedx/npm
            cyclonedx-npm --output-file sbom-npm.json
          fi
          # Combine SBOMs if both exist
          if [ -f sbom.json ] && [ -f sbom-npm.json ]; then
            python << 'EOFPYTHON'
import json
with open('sbom.json') as f:
  sbom = json.load(f)
with open('sbom-npm.json') as f:
  sbom_npm = json.load(f)
# Merge components
if 'components' not in sbom:
  sbom['components'] = []
sbom['components'].extend(sbom_npm.get('components', []))
with open('sbom.json', 'w') as f:
  json.dump(sbom, f, indent=2)
EOFPYTHON
          fi
          echo "✓ SBOM generated: sbom.json"
        continue-on-error: true

      # License compliance check
      - name: Check license compliance
        if: inputs.scan-dependencies
        run: |
          python -m pip install pip-licenses
          echo "## License Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          pip-licenses --format markdown >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

      # Code scanning with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'python,javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Vulnerability detection
      - name: Check for vulnerabilities
        id: vulnscan
        run: |
          vulnerabilities_found=false
          if [ -f dependency-scan.json ] && grep -q '"vulnerabilities"' dependency-scan.json; then
            vulnerabilities_found=true
          fi
          if [ -f trivy-scan.json ] && [ -s trivy-scan.json ]; then
            vulnerabilities_found=true
          fi
          echo "vulnerabilities-found=$vulnerabilities_found" >> $GITHUB_OUTPUT
          if [ "$vulnerabilities_found" = "true" ] && [ "${{ inputs.fail-on-critical }}" = "true" ]; then
            echo "❌ Critical vulnerabilities found"
            exit 1
          fi
        continue-on-error: false

      # Upload scan results
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            dependency-scan.json
            dependency-scan-npm.json
            trivy-scan.json
            sbom.json
            sbom-npm.json
          retention-days: 30

      # Summary
      - name: Security Summary
        if: always()
        run: |
          echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "- Container Scan: ${{ inputs.scan-container }}" >> $GITHUB_STEP_SUMMARY
          echo "- Dependency Scan: ${{ inputs.scan-dependencies }}" >> $GITHUB_STEP_SUMMARY
          echo "- SBOM Generated: sbom.json" >> $GITHUB_STEP_SUMMARY
          if [ -f dependency-scan.json ]; then
            echo "- Dependency Results: [artifact]($(echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))" >> $GITHUB_STEP_SUMMARY
          fi
