apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatekeeper-metrics
  namespace: gatekeeper-system
  labels:
    app: gatekeeper
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: gatekeeper
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
  labels:
    app: gatekeeper
spec:
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: gatekeeper
