name: Container Build and Push
description: Build and push container image with security scanning

inputs:
  image-name:
    description: Name of the container image
    required: true
  registry:
    description: Container registry (e.g., ghcr.io)
    required: true
    default: ghcr.io
  dockerfile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ github.sha }}
          ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ github.sha }}
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
        category: trivy-container-scan
