# Kubernetes manifests for platform demo application
# This file contains Deployment, Service, and HorizontalPodAutoscaler resources

---
# Deployment: Manages the lifecycle of demo application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo-app
  labels:
    app: platform-demo-app
    version: v1
  annotations:
    description: "Platform demo application for Chapter 5: Evaluate User Experience"

spec:
  # Number of replicas for high availability
  replicas: 2

  # Pod selector
  selector:
    matchLabels:
      app: platform-demo-app

  # Deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: platform-demo-app
        version: v1
      annotations:
        prometheus.io/scrape: "false"

    spec:
      # Security context for the pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      containers:
      - name: app
        # Container image
        image: platform-demo-app:latest
        imagePullPolicy: Never  # Use local image for demo

        # Port configuration
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP

        # Startup probe - gives app time to start
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 10

        # Liveness probe - restart if unhealthy
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        # Readiness probe - remove from traffic if not ready
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        # Resource requests and limits
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi

        # Security context for container
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL

        # Environment variables
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_ENV
          value: "production"

---
# Service: Exposes the deployment internally
apiVersion: v1
kind: Service
metadata:
  name: platform-demo-app
  labels:
    app: platform-demo-app

spec:
  type: ClusterIP
  selector:
    app: platform-demo-app

  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

  sessionAffinity: None

---
# HorizontalPodAutoscaler: Scales based on CPU usage
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: platform-demo-app-hpa
  labels:
    app: platform-demo-app

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform-demo-app

  # Min and max replicas
  minReplicas: 2
  maxReplicas: 5

  # Scaling metrics
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# PodDisruptionBudget: Ensures availability during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-demo-app-pdb

spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: platform-demo-app
