# xrd-gpu-nodepool.yaml
# Composite Resource Definition for GPU node pools
# Enables ML teams to request GPU resources with governance controls

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: gpunodepools.compute.platform.io
spec:
  group: compute.platform.io
  names:
    kind: GPUNodePool
    plural: gpunodepools
  claimNames:
    kind: GPUNodePoolClaim
    plural: gpunodepoolclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    gpuType:
                      type: string
                      description: GPU type
                      enum: [nvidia-t4, nvidia-a10g, nvidia-a100]
                      default: nvidia-t4
                    nodeCount:
                      type: integer
                      description: Number of GPU nodes
                      minimum: 1
                      maximum: 10
                      default: 1
                    spotInstances:
                      type: boolean
                      description: Use spot instances for cost savings
                      default: true
                    schedulingWindow:
                      type: object
                      description: When nodes should be available
                      properties:
                        startHour:
                          type: integer
                          minimum: 0
                          maximum: 23
                        endHour:
                          type: integer
                          minimum: 0
                          maximum: 23
                        timezone:
                          type: string
                          default: UTC
                  required:
                    - gpuType
